version: '2.1'

networks:
    mediun_confirmation_ms-dev:
        driver: bridge

services:
	#Mediun-Notif
	db:
		image: postgres
		volumes:
		  - ./tmp/db:/var/lib/postgresql/data
	  web:
		build: .
		command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
		volumes:
		  - .:/myapp
		ports:
		  - "5004:3000"
		depends_on:
		  - db

	#Mediun-Confirmation
    mysql_image:
        image: mysql:latest
        ports:
            - "6002:3006"
        restart: always
        volumes:
            - ./dbscripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: "123"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "Confirmpass200"
            MYSQL_DB: "Confirmations"
        networks:
            - mediun_confirmation_ms-dev

    mediun_confirmation_ms:
        image: mediun_confirmation_ms
        depends_on:
            - "mysql_image"
        build:    
            context: .
            dockerfile: Dockerfile
        ports:
            - "5002:80"
        environment:
            DB_CONNECTION_STRING: "server=localhost;port=6002;database=Confirmations;uid=root;password=Confirmpass200"
        networks:
            - mediun_confirmation_ms-dev

	#Mediun-crypto

  	mediun-crypto-ms:
    	build: ./
    	restart: on-failure
    	ports:
    	  - "5001:5001"
    	links:
     	 - mediun-crypto-db:networkcrypto
 	  mediun-crypto-db:
    	image: mongo:4.2.0
    	ports:
      	- "6001:27017"

	#Mediun-appointment

	  mediun-appointment-ms:
    	build: .
    	ports:
     	- "5005:5005"
    	links:
     	- mediun-appointment-db:network_appointment
  	mediun-appointment-db:
    	image: mongo
    	restart: always
    	ports:
     	- "6005:27017"

	#Mediun-authentication

	
  authentication_db:
    image: nouchka/sqlite3:latest
    ports:
      - "3001:3001"
    volumes:
      - ./db/development.sqlite3

  authentication_ms:
    build: .
    # command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:setup && bundle exec rails s -p 5003 -b 0.0.0.0 && rm authentication_ms/tmp/pids/server.pid"
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:setup && rm -f /authentication_ms/tmp/pids/server.pid && bundle exec rails s -p 5003 -b 0.0.0.0"
    ports:
      - "5003:5003"
    depends_on:
      - authentication_db

	#API-Gateway usando GraphQL
    mediun_api:
    	build: .
	    environment:
    	  PORT: '5000'
	      SHOW_URLS: 'true'
	      COMMON_URL: '192.168.0.13'

		  #MS_CRYPTO_VARIABLES
		  CRYPTO_URL: '35.240.32.29'
		  CRYPTO_PORT: '5001'
		  CRYPTO_ENTRY: 'crypto'
		  #MS_CONFIRMATION_VARIABLES
		  CONFIRMATION_URL: '35.203.125.249'
		  CONFIRMATION_PORT: '5002'
		  CONFIRMATION_USERS_ENTRY: 'api/confirmation'
		  #MS_AUTH_VARIABLES
		  AUTH_URL: '35.238.81.164'
		  AUTH_PORT: '5003'
		  AUTH_ENTRY: 'auth'
		  USERS_ENTRY: 'users'    
		  #MS_NOTIF_VARIABLES
		  NOTIF_URL:  '35.234.173.101'
		  NOTIF_PORT: '5004'
		  NOTIF_ENTRY: 'users'
		  #MS_APPOINTMENT_VARIABLES
		  APPOINTMENT_URL: '34.74.190.194'
		  APPOINTMENT_PORT: '5005'
		  APPOINTMENT_ENTRY: 'schedules'
		  #MS_EXCUSES_VARIABLES
		  EXCUSES_URL: '34.83.81.244'
		  EXCUSES_PORT: '5006'
		  EXCUSES_ENTRY: 'medical_excuses'
		  #MS_USERS_VARIABLES
		  USERS_URL: '192.168.0.13'
		  USERS_PORT: '5007'
		  USERS_ENTRY: 'users'
		ports:
		  - '5000:5000'

	#Proxy inverso tipo nginx
    mediun-proxy:
      build: ./sa-proxy/
      depends_on:
        - sa-api
      ports:
        - "80:80"
